// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AISettingsDO AI 连接配置。
 */
export class AISettingsDO {
    "apiBase": string;
    "hasApiKey": boolean;
    "model": string;
    "provider": string;

    /** Creates a new AISettingsDO instance. */
    constructor($$source: Partial<AISettingsDO> = {}) {
        if (!("apiBase" in $$source)) {
            this["apiBase"] = "";
        }
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISettingsDO instance from a string or object.
     */
    static createFrom($$source: any = {}): AISettingsDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISettingsDO($$parsedSource as Partial<AISettingsDO>);
    }
}

/**
 * AISettingsSaveDO 保存 AI 配置。
 */
export class AISettingsSaveDO {
    "apiBase": string;
    "apiKey": string;
    "model": string;
    "provider": string;

    /** Creates a new AISettingsSaveDO instance. */
    constructor($$source: Partial<AISettingsSaveDO> = {}) {
        if (!("apiBase" in $$source)) {
            this["apiBase"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISettingsSaveDO instance from a string or object.
     */
    static createFrom($$source: any = {}): AISettingsSaveDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISettingsSaveDO($$parsedSource as Partial<AISettingsSaveDO>);
    }
}

/**
 * AppInfoDO 应用信息。
 */
export class AppInfoDO {
    "version": string;
    "name": string;

    /** Creates a new AppInfoDO instance. */
    constructor($$source: Partial<AppInfoDO> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfoDO instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfoDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfoDO($$parsedSource as Partial<AppInfoDO>);
    }
}

/**
 * CatalogNodeDO 章节树节点：chapter 为章节容器，page 为章节下的解读页。
 */
export class CatalogNodeDO {
    "id": string;
    "sessionId": string;
    "parentId": string;

    /**
     * chapter | page
     */
    "kind": string;
    "title": string;
    "snapId": string;
    "sortOrder": number;

    /** Creates a new CatalogNodeDO instance. */
    constructor($$source: Partial<CatalogNodeDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("snapId" in $$source)) {
            this["snapId"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogNodeDO instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogNodeDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogNodeDO($$parsedSource as Partial<CatalogNodeDO>);
    }
}

/**
 * CatalogNodeSaveDO 新建或更新目录节点。
 */
export class CatalogNodeSaveDO {
    "id": string;
    "parentId": string;
    "kind": string;
    "title": string;
    "snapId": string;

    /** Creates a new CatalogNodeSaveDO instance. */
    constructor($$source: Partial<CatalogNodeSaveDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("snapId" in $$source)) {
            this["snapId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogNodeSaveDO instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogNodeSaveDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogNodeSaveDO($$parsedSource as Partial<CatalogNodeSaveDO>);
    }
}

/**
 * CatalogSettingsDO 目录入库方式。
 */
export class CatalogSettingsDO {
    "autoAdd": boolean;

    /** Creates a new CatalogSettingsDO instance. */
    constructor($$source: Partial<CatalogSettingsDO> = {}) {
        if (!("autoAdd" in $$source)) {
            this["autoAdd"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogSettingsDO instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogSettingsDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogSettingsDO($$parsedSource as Partial<CatalogSettingsDO>);
    }
}

/**
 * LayoutSettingsDO 笔记窗口布局设置（前端可见）。
 */
export class LayoutSettingsDO {
    "docked": boolean;
    "sidebarW": number;
    "notePlace": string;

    /** Creates a new LayoutSettingsDO instance. */
    constructor($$source: Partial<LayoutSettingsDO> = {}) {
        if (!("docked" in $$source)) {
            this["docked"] = false;
        }
        if (!("sidebarW" in $$source)) {
            this["sidebarW"] = 0;
        }
        if (!("notePlace" in $$source)) {
            this["notePlace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LayoutSettingsDO instance from a string or object.
     */
    static createFrom($$source: any = {}): LayoutSettingsDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LayoutSettingsDO($$parsedSource as Partial<LayoutSettingsDO>);
    }
}

/**
 * PromptSettingsDO 提示词模板集合与当前选中项。
 */
export class PromptSettingsDO {
    "activeId": string;
    "templates": PromptTemplateDO[];

    /** Creates a new PromptSettingsDO instance. */
    constructor($$source: Partial<PromptSettingsDO> = {}) {
        if (!("activeId" in $$source)) {
            this["activeId"] = "";
        }
        if (!("templates" in $$source)) {
            this["templates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptSettingsDO instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptSettingsDO {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("templates" in $$parsedSource) {
            $$parsedSource["templates"] = $$createField1_0($$parsedSource["templates"]);
        }
        return new PromptSettingsDO($$parsedSource as Partial<PromptSettingsDO>);
    }
}

/**
 * PromptTemplateDO 解读提示词模板。
 */
export class PromptTemplateDO {
    "id": string;
    "name": string;
    "systemPrompt": string;

    /** Creates a new PromptTemplateDO instance. */
    constructor($$source: Partial<PromptTemplateDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplateDO instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplateDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptTemplateDO($$parsedSource as Partial<PromptTemplateDO>);
    }
}

/**
 * PromptTemplateSaveDO 保存/更新模板。
 */
export class PromptTemplateSaveDO {
    "id": string;
    "name": string;
    "systemPrompt": string;

    /** Creates a new PromptTemplateSaveDO instance. */
    constructor($$source: Partial<PromptTemplateSaveDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplateSaveDO instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplateSaveDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptTemplateSaveDO($$parsedSource as Partial<PromptTemplateSaveDO>);
    }
}

/**
 * ReaderSettingsDO 侧栏阅读样式。
 */
export class ReaderSettingsDO {
    "fontSize": number;
    "lineHeight": number;
    "fontFamily": string;
    "paragraphGap": number;

    /**
     * magazine minimal academic terminal card brief
     */
    "layoutTheme": string;

    /** Creates a new ReaderSettingsDO instance. */
    constructor($$source: Partial<ReaderSettingsDO> = {}) {
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            this["lineHeight"] = 0;
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("paragraphGap" in $$source)) {
            this["paragraphGap"] = 0;
        }
        if (!("layoutTheme" in $$source)) {
            this["layoutTheme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReaderSettingsDO instance from a string or object.
     */
    static createFrom($$source: any = {}): ReaderSettingsDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReaderSettingsDO($$parsedSource as Partial<ReaderSettingsDO>);
    }
}

/**
 * RegionDO 框选区域（相对 overlay 窗口内容区，DIP 像素）。
 */
export class RegionDO {
    "x": number;
    "y": number;
    "w": number;
    "h": number;

    /** Creates a new RegionDO instance. */
    constructor($$source: Partial<RegionDO> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegionDO instance from a string or object.
     */
    static createFrom($$source: any = {}): RegionDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegionDO($$parsedSource as Partial<RegionDO>);
    }
}

/**
 * SessionDO 一本读书笔记（持久化表名仍为 sessions）。
 */
export class SessionDO {
    "id": string;
    "notebookName": string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new SessionDO instance. */
    constructor($$source: Partial<SessionDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("notebookName" in $$source)) {
            this["notebookName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDO instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionDO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionDO($$parsedSource as Partial<SessionDO>);
    }
}

/**
 * SnapDO 单次解读快照。
 */
export class SnapDO {
    "id": string;
    "sessionId": string;
    "title": string;
    "ocrText": string;
    "summary": string;
    "concepts": string[];
    "createdAt": number;

    /** Creates a new SnapDO instance. */
    constructor($$source: Partial<SnapDO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("ocrText" in $$source)) {
            this["ocrText"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("concepts" in $$source)) {
            this["concepts"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapDO instance from a string or object.
     */
    static createFrom($$source: any = {}): SnapDO {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("concepts" in $$parsedSource) {
            $$parsedSource["concepts"] = $$createField5_0($$parsedSource["concepts"]);
        }
        return new SnapDO($$parsedSource as Partial<SnapDO>);
    }
}

// Private type creation functions
const $$createType0 = PromptTemplateDO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
