//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../../../../wread/internal/model/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "catalog:changed": $$createType0,
        "notebook:opened": $$createType1,
        "read:done": $$createType2,
        "reader:settings": $$createType3,
    }));
}

// Private type creation functions
const $$createType0 = model$0.CatalogNodeDO.createFrom;
const $$createType1 = model$0.SessionDO.createFrom;
const $$createType2 = model$0.SnapDO.createFrom;
const $$createType3 = model$0.ReaderSettingsDO.createFrom;

configure();
