// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../../wread/internal/model/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "catalog:changed": model$0.CatalogNodeDO;
            "focus:note": boolean;
            "layout:docked": boolean;
            "layout:notePlace": string;
            "layout:sidebarW": number;
            "notebook:opened": model$0.SessionDO;
            "overlay:editable": boolean;
            "overlay:scopeMode": string;
            "pill:restored": string;
            "read:continuous": boolean;
            "read:continuousStop": string;
            "read:delta": string;
            "read:done": model$0.SnapDO;
            "read:error": string;
            "read:followup": string;
            "read:ocr": string;
            "read:preview": string;
            "read:settings": model$0.ReadSettingsDO;
            "read:status": string;
            "reader:settings": model$0.ReaderSettingsDO;
        }
    }
}
