// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service Wails 绑定服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AddToCatalog 手动将解读页归入章节。
 */
export function AddToCatalog(chapterID: string, snapID: string, title: string): $CancellablePromise<model$0.CatalogNodeDO> {
    return $Call.ByID(1808543182, chapterID, snapID, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AskFollowUp 追问。
 */
export function AskFollowUp(question: string): $CancellablePromise<string> {
    return $Call.ByID(1303153300, question);
}

/**
 * CreateChapter 新建章节。
 */
export function CreateChapter(parentID: string, title: string): $CancellablePromise<model$0.CatalogNodeDO> {
    return $Call.ByID(197153644, parentID, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateNotebook 新建笔记本并打开。
 */
export function CreateNotebook(title: string): $CancellablePromise<model$0.SessionDO> {
    return $Call.ByID(3051788550, title).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DefaultRegion 返回开卷区内默认阅读区域（相对工作区左上角）。
 */
export function DefaultRegion(): $CancellablePromise<model$0.RegionDO> {
    return $Call.ByID(1095506736).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DeleteCatalogNode 删除目录节点及子树。
 */
export function DeleteCatalogNode(id: string): $CancellablePromise<void> {
    return $Call.ByID(22570791, id);
}

/**
 * DeleteNotebook 删除笔记本；若删的是当前本则返回新的当前本。
 */
export function DeleteNotebook(id: string): $CancellablePromise<model$0.SessionDO> {
    return $Call.ByID(2979111865, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeletePromptTemplate 删除解读模板。
 */
export function DeletePromptTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(390305792, id);
}

/**
 * EnsureOverlayReadMode 布局就绪后同步开卷穿透状态。
 */
export function EnsureOverlayReadMode(): $CancellablePromise<void> {
    return $Call.ByID(2947331572);
}

/**
 * FocusOverlay 聚焦工作区并进入开卷调整模式。
 */
export function FocusOverlay(): $CancellablePromise<void> {
    return $Call.ByID(832544907);
}

/**
 * FocusSidebar 聚焦笔记（内嵌时同工作区，弹出时聚焦弹出窗）。
 */
export function FocusSidebar(): $CancellablePromise<void> {
    return $Call.ByID(2525716303);
}

/**
 * GetAISettings 读取 AI 配置。
 */
export function GetAISettings(): $CancellablePromise<model$0.AISettingsDO> {
    return $Call.ByID(1169761906).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetActiveNotebook 返回当前打开的笔记本。
 */
export function GetActiveNotebook(): $CancellablePromise<model$0.SessionDO> {
    return $Call.ByID(1329623418).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetActiveNotebookName 当前笔记本名称。
 */
export function GetActiveNotebookName(): $CancellablePromise<string> {
    return $Call.ByID(3323509217);
}

/**
 * GetAppInfo 返回应用信息。
 */
export function GetAppInfo(): $CancellablePromise<model$0.AppInfoDO> {
    return $Call.ByID(810134192).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetCatalogInsertParent 读取当前归入目标章节 ID。
 */
export function GetCatalogInsertParent(): $CancellablePromise<string> {
    return $Call.ByID(273863205);
}

/**
 * GetCatalogSettings 读取目录入库方式。
 */
export function GetCatalogSettings(): $CancellablePromise<model$0.CatalogSettingsDO> {
    return $Call.ByID(954548741).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetLayoutSettings 读取笔记布局设置。
 */
export function GetLayoutSettings(): $CancellablePromise<model$0.LayoutSettingsDO> {
    return $Call.ByID(1358181746).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetPromptSettings 读取解读提示词模板。
 */
export function GetPromptSettings(): $CancellablePromise<model$0.PromptSettingsDO> {
    return $Call.ByID(2411867014).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetReaderSettings 读取侧栏阅读样式。
 */
export function GetReaderSettings(): $CancellablePromise<model$0.ReaderSettingsDO> {
    return $Call.ByID(1389044899).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetReadingMode 开卷是否处于阅读穿透模式。
 */
export function GetReadingMode(): $CancellablePromise<boolean> {
    return $Call.ByID(3504571844);
}

/**
 * HideOverlay 隐藏工作区。
 */
export function HideOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2987718969);
}

/**
 * HideSidebar 隐藏弹出笔记窗。
 */
export function HideSidebar(): $CancellablePromise<void> {
    return $Call.ByID(976447573);
}

/**
 * InterpretNow 解读开卷区内区域。
 */
export function InterpretNow(region: model$0.RegionDO): $CancellablePromise<void> {
    return $Call.ByID(1834235840, region);
}

/**
 * ListCatalog 列出当前会话目录树。
 */
export function ListCatalog(): $CancellablePromise<model$0.CatalogNodeDO[]> {
    return $Call.ByID(1689678366).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListNotebooks 列出全部笔记本。
 */
export function ListNotebooks(): $CancellablePromise<model$0.SessionDO[]> {
    return $Call.ByID(1945990983).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSessions 列出读书会话。
 */
export function ListSessions(): $CancellablePromise<model$0.SessionDO[]> {
    return $Call.ByID(1975139466).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSnaps 列出当前会话解读记录。
 */
export function ListSnaps(): $CancellablePromise<model$0.SnapDO[]> {
    return $Call.ByID(2592071840).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * MoveCatalogNode 拖动调整目录节点父级与排序。
 */
export function MoveCatalogNode(nodeID: string, parentID: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(840469801, nodeID, parentID, index);
}

/**
 * OpenNotebook 打开笔记本。
 */
export function OpenNotebook(id: string): $CancellablePromise<model$0.SessionDO> {
    return $Call.ByID(2384889266, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetPromptTemplates 恢复默认解读模板。
 */
export function ResetPromptTemplates(): $CancellablePromise<model$0.PromptSettingsDO> {
    return $Call.ByID(3283912883).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveAISettings 保存 AI 配置。
 */
export function SaveAISettings($in: model$0.AISettingsSaveDO): $CancellablePromise<void> {
    return $Call.ByID(107156617, $in);
}

/**
 * SavePromptTemplate 新建或更新解读模板。
 */
export function SavePromptTemplate($in: model$0.PromptTemplateSaveDO): $CancellablePromise<model$0.PromptTemplateDO> {
    return $Call.ByID(2547522166, $in).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SaveReaderSettings 保存侧栏阅读样式。
 */
export function SaveReaderSettings($in: model$0.ReaderSettingsDO): $CancellablePromise<void> {
    return $Call.ByID(3249227796, $in);
}

/**
 * SelectSnap 选中目录页并设为追问上下文。
 */
export function SelectSnap(snapID: string): $CancellablePromise<model$0.SnapDO> {
    return $Call.ByID(1907960539, snapID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SetActiveNotebookName 设置当前笔记本名称。
 */
export function SetActiveNotebookName(name: string): $CancellablePromise<void> {
    return $Call.ByID(2495388165, name);
}

/**
 * SetActivePromptTemplate 切换当前解读模板。
 */
export function SetActivePromptTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(3415244383, id);
}

/**
 * SetCatalogAutoAdd 切换自动/手动入目录。
 */
export function SetCatalogAutoAdd(auto: boolean): $CancellablePromise<void> {
    return $Call.ByID(1624206358, auto);
}

/**
 * SetCatalogInsertParent 设置当前选中章节。
 */
export function SetCatalogInsertParent(chapterID: string): $CancellablePromise<void> {
    return $Call.ByID(788222321, chapterID);
}

/**
 * SetNotePlace 设置笔记停靠方位：right left top bottom center popout。
 */
export function SetNotePlace(place: string): $CancellablePromise<void> {
    return $Call.ByID(4043653024, place);
}

/**
 * SetReadingMode 切换阅读穿透模式。
 */
export function SetReadingMode(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1420050496, on);
}

/**
 * SetSidebarWidth 设置内嵌笔记栏宽度。
 */
export function SetSidebarWidth(width: number): $CancellablePromise<void> {
    return $Call.ByID(4041747925, width);
}

/**
 * ShowOverlay 显示工作区。
 */
export function ShowOverlay(): $CancellablePromise<void> {
    return $Call.ByID(2886028262);
}

/**
 * ShowSidebar 显示笔记。
 */
export function ShowSidebar(): $CancellablePromise<void> {
    return $Call.ByID(566389010);
}

/**
 * SyncPopoutBounds 将弹出笔记窗 bounds 写入持久化。
 */
export function SyncPopoutBounds(): $CancellablePromise<void> {
    return $Call.ByID(3578349832);
}

/**
 * SyncWorkspaceBounds 将工作区窗口 bounds 写入持久化。
 */
export function SyncWorkspaceBounds(): $CancellablePromise<void> {
    return $Call.ByID(1866673084);
}

/**
 * TestAIConnection 测试 AI 连接。
 */
export function TestAIConnection(): $CancellablePromise<void> {
    return $Call.ByID(3312246565);
}

/**
 * UpdateCatalogNode 更新目录节点。
 */
export function UpdateCatalogNode($in: model$0.CatalogNodeSaveDO): $CancellablePromise<model$0.CatalogNodeDO> {
    return $Call.ByID(986189777, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.CatalogNodeDO.createFrom;
const $$createType1 = model$0.SessionDO.createFrom;
const $$createType2 = model$0.RegionDO.createFrom;
const $$createType3 = model$0.AISettingsDO.createFrom;
const $$createType4 = model$0.AppInfoDO.createFrom;
const $$createType5 = model$0.CatalogSettingsDO.createFrom;
const $$createType6 = model$0.LayoutSettingsDO.createFrom;
const $$createType7 = model$0.PromptSettingsDO.createFrom;
const $$createType8 = model$0.ReaderSettingsDO.createFrom;
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType1);
const $$createType11 = model$0.SnapDO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = model$0.PromptTemplateDO.createFrom;
